/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TrainsTicket;

    import java.awt.Color;
    import java.text.SimpleDateFormat;
    import  java.util.Calendar;
    import  java.util.Random;
/**
 *
 * @author user
 */
public class TrainTicket extends javax.swing.JFrame {

    /**
     * Creates new form TrainTicket
     */
    public TrainTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRbStd = new javax.swing.JRadioButton();
        jRbSingle = new javax.swing.JRadioButton();
        jRbAdultYes = new javax.swing.JRadioButton();
        jRbChildYes = new javax.swing.JRadioButton();
        jRbEco = new javax.swing.JRadioButton();
        jRbReturn = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRbFirst = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtSubTotal = new javax.swing.JTextField();
        jtTax = new javax.swing.JTextField();
        jtTotal = new javax.swing.JTextField();
        btnTotal = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtClass = new javax.swing.JTextField();
        jtType = new javax.swing.JTextField();
        jtAdult = new javax.swing.JTextField();
        jtChild = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jFrom = new javax.swing.JTextField();
        jTo = new javax.swing.JTextField();
        jDate = new javax.swing.JTextField();
        jTime = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jtTNo = new javax.swing.JTextField();
        jtPrice = new javax.swing.JTextField();
        jtRoute = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 70)); // NOI18N
        jLabel1.setText("Train Ticketing System");

        jLabel2.setFont(new java.awt.Font("Webdings", 0, 96)); // NOI18N
        jLabel2.setText("o");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Class");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Ticket Type");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Adult");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Child");

        jRbStd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRbStd.setText("Standard");

        jRbSingle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRbSingle.setText("Single");

        jRbAdultYes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRbAdultYes.setText("Yes");

        jRbChildYes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRbChildYes.setText("Yes");

        jRbEco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRbEco.setText("Economy");

        jRbReturn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRbReturn.setText("Return");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Destination");

        jRbFirst.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jRbFirst.setText("First Class");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kilbum", "Queens Park", "Oxford", "Middlesex" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRbStd)
                            .addComponent(jRbEco)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel3)))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRbSingle)
                            .addComponent(jRbReturn)))
                    .addComponent(jRbFirst))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRbAdultYes)
                            .addComponent(jLabel5))
                        .addGap(143, 143, 143)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRbChildYes)
                            .addComponent(jLabel6)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jRbChildYes)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRbStd)
                            .addComponent(jRbSingle)
                            .addComponent(jRbAdultYes))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRbEco)
                            .addComponent(jRbReturn)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRbFirst)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Sub Total");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Tax");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Total");

        jtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jtTax.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jtTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        btnTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTotal.setText("Total");
        btnTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTotalMouseClicked(evt);
            }
        });
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtTax)
                    .addComponent(jtSubTotal)
                    .addComponent(jtTotal))
                .addGap(179, 179, 179))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(btnTotal)
                .addGap(91, 91, 91)
                .addComponent(btnReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(124, 124, 124))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotal)
                    .addComponent(btnReset)
                    .addComponent(btnExit))
                .addGap(31, 31, 31))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 0, 51), 4));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 0, 51), 4));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Class");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Ticket Type");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Adult");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Child");

        jtClass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jtType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jtAdult.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtAdult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtAdultActionPerformed(evt);
            }
        });

        jtChild.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtChild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtChildActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("From");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("To");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Date");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Time");

        jFrom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Ticket No.");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Price");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Route");

        jtTNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jtPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jtRoute.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel11))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jtClass, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtType, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jtAdult, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(jLabel13)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtChild, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel14)
                                        .addGap(63, 63, 63))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTime, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(313, 313, 313))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFrom, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(jTo))
                                .addGap(72, 72, 72)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel21)
                                    .addComponent(jtTNo, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(jtPrice)
                                    .addComponent(jtRoute))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(4, 4, 4))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtAdult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtChild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtTNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtRoute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtAdultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtAdultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtAdultActionPerformed

    private void jtChildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtChildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtChildActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.getContentPane().setBackground(Color.BLACK);
    }//GEN-LAST:event_formWindowActivated

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        jtSubTotal.setText(null);
        jtTax.setText(null);
        jtTotal.setText(null);
        jtClass.setText(null);
        jtType.setText(null);
        jtAdult.setText(null);
        jtChild.setText(null);
        jtTNo.setText(null);
        jtPrice.setText(null);
        jtRoute.setText(null); 
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
    //====================Time=======================   
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        jTime.setText(tTime.format(timer.getTime()));
        
    //=====================Date========================
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyyy");
        jDate.setText(Tdate.format(timer.getTime()));
        
        jFrom.setText("London *");
        jTo.setText((String) jComboBox1.getSelectedItem()+ "*");
        
    //=============Random number Generator================
        int num1;
        String q1 = "";
        num1 = 1325 + (int) (Math.random()*4238);
        q1 += num1 +1325;
        jtTNo.setText(q1);
        
    //=====================================================
        jtRoute.setText("ANY");
        
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTotalMouseClicked
        double tax = 19.50;
        double MilesK8 = 25.70;
        double MilesK12 = 25.10;
        double MilesK20 = 45.23;
        double MilesK30 = 55.98;
        double totalCost, eco = 3.85,fclass = 5.60;
        
    //=========Std===========Kilbum===========================
        if ((jRbStd.isSelected()) && (jRbSingle.isSelected()) && (jRbAdultYes.isSelected()) && jComboBox1.getSelectedItem().equals("Kilbum"))
        {
            totalCost = (tax * MilesK8)/100;
            String sTax = String.format("$%.2f", totalCost);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK8);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", MilesK8 +totalCost);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("STD");
            jtType.setText("ONE MAY");
            jtAdult.setText("ONE");
            jtChild.setText("NIL");  
        }
        else if ((jRbStd.isSelected()) && (jRbReturn.isSelected()) && (jRbAdultYes.isSelected()) && jComboBox1.getSelectedItem().equals("Kilbum"))
        {
            totalCost = (tax * (MilesK8)*2 )/100;
            String sTax = String.format("$%.2f", totalCost);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK8*2);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", (MilesK8 + totalCost)*2 );
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("STD");
            jtType.setText("RETURN");
            jtAdult.setText("ONE");
            jtChild.setText("NIL"); 
        }
        else if ((jRbStd.isSelected()) && (jRbSingle.isSelected()) && (jRbChildYes.isSelected()) && jComboBox1.getSelectedItem().equals("Kilbum"))
        {
            totalCost = (tax * (MilesK8)*2 )/100;
            String sTax = String.format("$%.2f", totalCost -18);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK8);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", (MilesK8 + totalCost) - 18);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("STD");
            jtType.setText("ONE WAY");
            jtAdult.setText("NIL");
            jtChild.setText("ONE"); 
        }
        else if ((jRbStd.isSelected()) && (jRbReturn.isSelected()) && (jRbChildYes.isSelected()) && jComboBox1.getSelectedItem().equals("Kilbum"))
        {
            totalCost = (tax * (MilesK8)*2 )/100;
            String sTax = String.format("$%.2f", totalCost -18);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK8*2);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", ((MilesK8 + totalCost)*2) - 18);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("STD");
            jtType.setText("ONE RETURN");
            jtAdult.setText("NIL");
            jtChild.setText("ONE"); 
        }
        
    //=======Std=========Queens Park===============================
        else if ((jRbStd.isSelected()) && (jRbSingle.isSelected()) && (jRbAdultYes.isSelected()) && jComboBox1.getSelectedItem().equals("Queens Park"))
        {
            totalCost = (tax * MilesK12)/100;
            String sTax = String.format("$%.2f", totalCost);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK12);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", MilesK12 +totalCost);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("STD");
            jtType.setText("ONE MAY");
            jtAdult.setText("ONE");
            jtChild.setText("NIL");  
        }
        else if ((jRbStd.isSelected()) && (jRbReturn.isSelected()) && (jRbAdultYes.isSelected()) && jComboBox1.getSelectedItem().equals("Queens Park"))
        {
            totalCost = (tax * (MilesK12)*2 )/100;
            String sTax = String.format("$%.2f", totalCost);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK12*2);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", (MilesK12 + totalCost)*2 );
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("STD");
            jtType.setText("RETURN");
            jtAdult.setText("ONE");
            jtChild.setText("NIL"); 
        }
        else if ((jRbStd.isSelected()) && (jRbSingle.isSelected()) && (jRbChildYes.isSelected()) && jComboBox1.getSelectedItem().equals("Queens Park"))
        {
            totalCost = (tax * (MilesK12)*2 )/100;
            String sTax = String.format("$%.2f", totalCost -18);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK12);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", (MilesK12 + totalCost) - 18);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("STD");
            jtType.setText("ONE WAY");
            jtAdult.setText("NIL");
            jtChild.setText("ONE"); 
        }
        else if ((jRbStd.isSelected()) && (jRbReturn.isSelected()) && (jRbChildYes.isSelected()) && jComboBox1.getSelectedItem().equals("Queens Park"))
        {
            totalCost = (tax * (MilesK12)*2 )/100;
            String sTax = String.format("$%.2f", totalCost -18);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK12*2);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", ((MilesK12 + totalCost)*2) - 18);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("STD");
            jtType.setText("ONE RETURN");
            jtAdult.setText("NIL");
            jtChild.setText("ONE"); 
        }
        
    //=========Std===========Oxford======================
        else if ((jRbStd.isSelected()) && (jRbSingle.isSelected()) && (jRbAdultYes.isSelected()) && jComboBox1.getSelectedItem().equals("Oxford"))
        {
            totalCost = (tax * MilesK20)/100;
            String sTax = String.format("$%.2f", totalCost);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK20);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", MilesK20 +totalCost);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("STD");
            jtType.setText("ONE MAY");
            jtAdult.setText("ONE");
            jtChild.setText("NIL");  
        }
        else if ((jRbStd.isSelected()) && (jRbReturn.isSelected()) && (jRbAdultYes.isSelected()) && jComboBox1.getSelectedItem().equals("Oxford"))
        {
            totalCost = (tax * (MilesK20)*2 )/100;
            String sTax = String.format("$%.2f", totalCost);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK20*2);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", (MilesK20 + totalCost)*2 );
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("STD");
            jtType.setText("RETURN");
            jtAdult.setText("ONE");
            jtChild.setText("NIL"); 
        }
        else if ((jRbStd.isSelected()) && (jRbSingle.isSelected()) && (jRbChildYes.isSelected()) && jComboBox1.getSelectedItem().equals("Oxford"))
        {
            totalCost = (tax * (MilesK20)*2 )/100;
            String sTax = String.format("$%.2f", totalCost -18);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK20);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", (MilesK20 + totalCost) - 18);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("STD");
            jtType.setText("ONE WAY");
            jtAdult.setText("NIL");
            jtChild.setText("ONE"); 
        }
        else if ((jRbStd.isSelected()) && (jRbReturn.isSelected()) && (jRbChildYes.isSelected()) && jComboBox1.getSelectedItem().equals("Oxford"))
        {
            totalCost = (tax * (MilesK20)*2 )/100;
            String sTax = String.format("$%.2f", totalCost -18);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK20*2);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", ((MilesK20 + totalCost)*2) - 18);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("STD");
            jtType.setText("ONE RETURN");
            jtAdult.setText("NIL");
            jtChild.setText("ONE"); 
        }
        
    //=========Std================Middlesex================
        else if ((jRbStd.isSelected()) && (jRbSingle.isSelected()) && (jRbAdultYes.isSelected()) && jComboBox1.getSelectedItem().equals("Middlesex"))
        {
            totalCost = (tax * MilesK30)/100;
            String sTax = String.format("$%.2f", totalCost);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK30);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", MilesK30 +totalCost);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("STD");
            jtType.setText("ONE MAY");
            jtAdult.setText("ONE");
            jtChild.setText("NIL");  
        }
        else if ((jRbStd.isSelected()) && (jRbReturn.isSelected()) && (jRbAdultYes.isSelected()) && jComboBox1.getSelectedItem().equals("Middlesex"))
        {
            totalCost = (tax * (MilesK30)*2 )/100;
            String sTax = String.format("$%.2f", totalCost);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK30*2);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", (MilesK30 + totalCost)*2 );
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("STD");
            jtType.setText("RETURN");
            jtAdult.setText("ONE");
            jtChild.setText("NIL"); 
        }
        else if ((jRbStd.isSelected()) && (jRbSingle.isSelected()) && (jRbChildYes.isSelected()) && jComboBox1.getSelectedItem().equals("Middlesex"))
        {
            totalCost = (tax * (MilesK30)*2 )/100;
            String sTax = String.format("$%.2f", totalCost -18);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK30);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", (MilesK30 + totalCost) - 18);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("STD");
            jtType.setText("ONE WAY");
            jtAdult.setText("NIL");
            jtChild.setText("ONE"); 
        }
        else if ((jRbStd.isSelected()) && (jRbReturn.isSelected()) && (jRbChildYes.isSelected()) && jComboBox1.getSelectedItem().equals("Middlesex"))
        {
            totalCost = (tax * (MilesK30)*2 )/100;
            String sTax = String.format("$%.2f", totalCost -18);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK30*2);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", ((MilesK30 + totalCost)*2) - 18);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("STD");
            jtType.setText("ONE RETURN");
            jtAdult.setText("NIL");
            jtChild.setText("ONE");  
        }
       
   
    //=========Eco===========Kilbum===========================
        else if ((jRbEco.isSelected()) && (jRbSingle.isSelected()) && (jRbAdultYes.isSelected()) && jComboBox1.getSelectedItem().equals("Kilbum"))
        {
            totalCost = (tax * (eco + MilesK8))/100;
            String sTax = String.format("$%.2f", totalCost);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK8 +eco);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", MilesK8 + eco + totalCost);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("ECONOMY");
            jtType.setText("ONE MAY");
            jtAdult.setText("ONE");
            jtChild.setText("NIL");  
        }
        else if ((jRbEco.isSelected()) && (jRbReturn.isSelected()) && (jRbAdultYes.isSelected()) && jComboBox1.getSelectedItem().equals("Kilbum"))
        {
            totalCost = (tax * (MilesK8)*2 )/100;
            String sTax = String.format("$%.2f", totalCost);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK8*2);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", (MilesK8 + totalCost)*2 );
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("ECONOMY");
            jtType.setText("RETURN");
            jtAdult.setText("ONE");
            jtChild.setText("NIL"); 
        }
        else if ((jRbEco.isSelected()) && (jRbSingle.isSelected()) && (jRbChildYes.isSelected()) && jComboBox1.getSelectedItem().equals("Kilbum"))
        {
            totalCost = (tax * (MilesK8 +eco ))/100;
            String sTax = String.format("$%.2f", (totalCost +eco ) -18);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK8 + eco );
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", (MilesK8 + eco + totalCost) - 18);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("ECONOMY");
            jtType.setText("ONE WAY");
            jtAdult.setText("NIL");
            jtChild.setText("ONE"); 
        }
        else if ((jRbEco.isSelected()) && (jRbReturn.isSelected()) && (jRbChildYes.isSelected()) && jComboBox1.getSelectedItem().equals("Kilbum"))
        {
            totalCost = (tax * (MilesK8)*2 )/100;
            String sTax = String.format("$%.2f", totalCost -18);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK8*2);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", ((MilesK8 + totalCost)*2) - 18);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("ECONOMY");
            jtType.setText("RETURN");
            jtAdult.setText("NIL");
            jtChild.setText("ONE"); 
        }
        
    //=======Eco=========Queens Park===============================
        else if ((jRbEco.isSelected()) && (jRbSingle.isSelected()) && (jRbAdultYes.isSelected()) && jComboBox1.getSelectedItem().equals("Queens Park"))
        {
            totalCost = (tax * MilesK12 + eco)/100;
            String sTax = String.format("$%.2f", totalCost);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK12 +eco);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", MilesK12 + eco + totalCost);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("ECONOMY");
            jtType.setText("ONE MAY");
            jtAdult.setText("ONE");
            jtChild.setText("NIL");  
        }
        else if ((jRbEco.isSelected()) && (jRbReturn.isSelected()) && (jRbAdultYes.isSelected()) && jComboBox1.getSelectedItem().equals("Queens Park"))
        {
            totalCost = (tax * (MilesK12)*2 )/100;
            String sTax = String.format("$%.2f", totalCost);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK12*2);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", (MilesK12 + totalCost)*2 );
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("ECONOMY");
            jtType.setText("RETURN");
            jtAdult.setText("ONE");
            jtChild.setText("NIL"); 
        }
        else if ((jRbEco.isSelected()) && (jRbSingle.isSelected()) && (jRbChildYes.isSelected()) && jComboBox1.getSelectedItem().equals("Queens Park"))
        {
            totalCost = (tax * (MilesK12 + eco)*2 )/100;
            String sTax = String.format("$%.2f", totalCost -18);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK12 + eco);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", (MilesK12 + eco + totalCost) - 18);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("ECONOMY");
            jtType.setText("ONE WAY");
            jtAdult.setText("NIL");
            jtChild.setText("ONE"); 
        }
        else if ((jRbEco.isSelected()) && (jRbReturn.isSelected()) && (jRbChildYes.isSelected()) && jComboBox1.getSelectedItem().equals("Queens Park"))
        {
            totalCost = (tax * (MilesK12)*2 )/100;
            String sTax = String.format("$%.2f", totalCost -18);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK12*2);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", ((MilesK12 + totalCost)*2) - 18);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("ECONOMY");
            jtType.setText("ONE RETURN");
            jtAdult.setText("NIL");
            jtChild.setText("ONE"); 
        }
        
    //=========Eco===========Oxford======================
        else if ((jRbEco.isSelected()) && (jRbSingle.isSelected()) && (jRbAdultYes.isSelected()) && jComboBox1.getSelectedItem().equals("Oxford"))
        {
            totalCost = (tax * MilesK20 + eco)/100;
            String sTax = String.format("$%.2f", totalCost);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK20 + eco);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", MilesK20 + eco + totalCost);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("ECONOMY");
            jtType.setText("ONE MAY");
            jtAdult.setText("ONE");
            jtChild.setText("NIL");  
        }
        else if ((jRbEco.isSelected()) && (jRbReturn.isSelected()) && (jRbAdultYes.isSelected()) && jComboBox1.getSelectedItem().equals("Oxford"))
        {
            totalCost = (tax * (MilesK20)*2 )/100;
            String sTax = String.format("$%.2f", totalCost);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK20*2);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", (MilesK20 + totalCost)*2 );
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("ECONOMY");
            jtType.setText("RETURN");
            jtAdult.setText("ONE");
            jtChild.setText("NIL"); 
        }
        else if ((jRbEco.isSelected()) && (jRbSingle.isSelected()) && (jRbChildYes.isSelected()) && jComboBox1.getSelectedItem().equals("Oxford"))
        {
            totalCost = (tax * (MilesK20 + eco) )/100;
            String sTax = String.format("$%.2f", totalCost -18);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK20 + eco);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", (MilesK20 + eco + totalCost) - 18);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("ECONOMY");
            jtType.setText("ONE WAY");
            jtAdult.setText("NIL");
            jtChild.setText("ONE"); 
        }
        else if ((jRbEco.isSelected()) && (jRbReturn.isSelected()) && (jRbChildYes.isSelected()) && jComboBox1.getSelectedItem().equals("Oxford"))
        {
            totalCost = (tax * (MilesK20)*2 )/100;
            String sTax = String.format("$%.2f", totalCost -18);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK20*2);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", ((MilesK20 + totalCost)*2) - 18);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("ECONOMY");
            jtType.setText("ONE RETURN");
            jtAdult.setText("NIL");
            jtChild.setText("ONE"); 
        }
        
    //=========Eco================Middlesex================
        else if ((jRbEco.isSelected()) && (jRbSingle.isSelected()) && (jRbAdultYes.isSelected()) && jComboBox1.getSelectedItem().equals("Middlesex"))
        {
            totalCost = (tax * (MilesK30 + eco))/100;
            String sTax = String.format("$%.2f", totalCost);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK30 + eco);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", MilesK30 + eco +totalCost);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("ECONOMY");
            jtType.setText("ONE MAY");
            jtAdult.setText("ONE");
            jtChild.setText("NIL");  
        }
        else if ((jRbEco.isSelected()) && (jRbReturn.isSelected()) && (jRbAdultYes.isSelected()) && jComboBox1.getSelectedItem().equals("Middlesex"))
        {
            totalCost = (tax * (MilesK30)*2 )/100;
            String sTax = String.format("$%.2f", totalCost);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK30*2);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", (MilesK30 + totalCost)*2 );
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("ECONOMY");
            jtType.setText("RETURN");
            jtAdult.setText("ONE");
            jtChild.setText("NIL"); 
        }
        else if ((jRbEco.isSelected()) && (jRbSingle.isSelected()) && (jRbChildYes.isSelected()) && jComboBox1.getSelectedItem().equals("Middlesex"))
        {
            totalCost = (tax * (MilesK30 + eco))/100;
            String sTax = String.format("$%.2f", totalCost -18);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK30 + eco);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", (MilesK30 + eco + totalCost) -18);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("ECONOMY");
            jtType.setText("ONE WAY");
            jtAdult.setText("NIL");
            jtChild.setText("ONE"); 
        }
        else if ((jRbEco.isSelected()) && (jRbReturn.isSelected()) && (jRbChildYes.isSelected()) && jComboBox1.getSelectedItem().equals("Middlesex"))
        {
            totalCost = (tax * (MilesK30)*2 )/100;
            String sTax = String.format("$%.2f", totalCost -18);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK30*2);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", ((MilesK30 + totalCost)*2) - 18);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("ECONOMY");
            jtType.setText("ONE RETURN");
            jtAdult.setText("NIL");
            jtChild.setText("ONE"); 
        }
        
        
    //==========First Class========Kilbum===============
        else if ((jRbFirst.isSelected()) && (jRbSingle.isSelected()) && (jRbAdultYes.isSelected()) && jComboBox1.getSelectedItem().equals("Kilbum"))
        {
            totalCost = (tax * (fclass + MilesK8))/100;
            String sTax = String.format("$%.2f", totalCost);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK8 +fclass);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", MilesK8 + fclass + totalCost);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("First");
            jtType.setText("ONE MAY");
            jtAdult.setText("ONE");
            jtChild.setText("NIL");  
        }
        else if ((jRbFirst.isSelected()) && (jRbReturn.isSelected()) && (jRbAdultYes.isSelected()) && jComboBox1.getSelectedItem().equals("Kilbum"))
        {
            totalCost = (tax * (MilesK8)*2 )/100;
            String sTax = String.format("$%.2f", totalCost);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK8*2);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", (MilesK8 + totalCost)*2 );
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("First");
            jtType.setText("RETURN");
            jtAdult.setText("ONE");
            jtChild.setText("NIL"); 
        }
        else if ((jRbFirst.isSelected()) && (jRbSingle.isSelected()) && (jRbChildYes.isSelected()) && jComboBox1.getSelectedItem().equals("Kilbum"))
        {
            totalCost = (tax * (MilesK8 + fclass ))/100;
            String sTax = String.format("$%.2f", (totalCost +fclass ) -18);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK8 + fclass );
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", (MilesK8 + fclass + totalCost) - 18);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("First");
            jtType.setText("ONE WAY");
            jtAdult.setText("NIL");
            jtChild.setText("ONE"); 
        }
        else if ((jRbFirst.isSelected()) && (jRbReturn.isSelected()) && (jRbChildYes.isSelected()) && jComboBox1.getSelectedItem().equals("Kilbum"))
        {
            totalCost = (tax * (MilesK8)*2 )/100;
            String sTax = String.format("$%.2f", totalCost -18);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK8*2);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", ((MilesK8 + totalCost)*2) - 18);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("First");
            jtType.setText("RETURN");
            jtAdult.setText("NIL");
            jtChild.setText("ONE"); 
        }
        
    //======First Class=========Queens Park===============================
        else if ((jRbFirst.isSelected()) && (jRbSingle.isSelected()) && (jRbAdultYes.isSelected()) && jComboBox1.getSelectedItem().equals("Queens Park"))
        {
            totalCost = (tax * MilesK12 + fclass)/100;
            String sTax = String.format("$%.2f", totalCost);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK12 + fclass);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", MilesK12 + fclass + totalCost);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("First");
            jtType.setText("ONE MAY");
            jtAdult.setText("ONE");
            jtChild.setText("NIL");  
        }
        else if ((jRbFirst.isSelected()) && (jRbReturn.isSelected()) && (jRbAdultYes.isSelected()) && jComboBox1.getSelectedItem().equals("Queens Park"))
        {
            totalCost = (tax * (MilesK12)*2 )/100;
            String sTax = String.format("$%.2f", totalCost);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK12*2);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", (MilesK12 + totalCost)*2 );
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("First");
            jtType.setText("RETURN");
            jtAdult.setText("ONE");
            jtChild.setText("NIL"); 
        }
        else if ((jRbFirst.isSelected()) && (jRbSingle.isSelected()) && (jRbChildYes.isSelected()) && jComboBox1.getSelectedItem().equals("Queens Park"))
        {
            totalCost = (tax * (MilesK12 + fclass)*2 )/100;
            String sTax = String.format("$%.2f", totalCost -18);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK12 + fclass);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", (MilesK12 + fclass + totalCost) - 18);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("First");
            jtType.setText("ONE WAY");
            jtAdult.setText("NIL");
            jtChild.setText("ONE"); 
        }
        else if ((jRbFirst.isSelected()) && (jRbReturn.isSelected()) && (jRbChildYes.isSelected()) && jComboBox1.getSelectedItem().equals("Queens Park"))
        {
            totalCost = (tax * (MilesK12)*2 )/100;
            String sTax = String.format("$%.2f", totalCost -18);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK12*2);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", ((MilesK12 + totalCost)*2) - 18);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("First");
            jtType.setText("ONE RETURN");
            jtAdult.setText("NIL");
            jtChild.setText("ONE"); 
        }
        
    //=========First Class===========Oxford======================
        else if ((jRbFirst.isSelected()) && (jRbSingle.isSelected()) && (jRbAdultYes.isSelected()) && jComboBox1.getSelectedItem().equals("Oxford"))
        {
            totalCost = (tax * MilesK20 + fclass )/100;
            String sTax = String.format("$%.2f", totalCost);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK20 + fclass);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", MilesK20 + fclass + totalCost);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("First");
            jtType.setText("ONE MAY");
            jtAdult.setText("ONE");
            jtChild.setText("NIL");  
        }
        else if ((jRbFirst.isSelected()) && (jRbReturn.isSelected()) && (jRbAdultYes.isSelected()) && jComboBox1.getSelectedItem().equals("Oxford"))
        {
            totalCost = (tax * (MilesK20)*2 )/100;
            String sTax = String.format("$%.2f", totalCost);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK20*2);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", (MilesK20 + totalCost)*2 );
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("First");
            jtType.setText("RETURN");
            jtAdult.setText("ONE");
            jtChild.setText("NIL"); 
        }
        else if ((jRbFirst.isSelected()) && (jRbSingle.isSelected()) && (jRbChildYes.isSelected()) && jComboBox1.getSelectedItem().equals("Oxford"))
        {
            totalCost = (tax * (MilesK20 + fclass) )/100;
            String sTax = String.format("$%.2f", totalCost -18);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK20 + fclass);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", (MilesK20 + fclass + totalCost) - 18);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("First");
            jtType.setText("ONE WAY");
            jtAdult.setText("NIL");
            jtChild.setText("ONE"); 
        }
        else if ((jRbFirst.isSelected()) && (jRbReturn.isSelected()) && (jRbChildYes.isSelected()) && jComboBox1.getSelectedItem().equals("Oxford"))
        {
            totalCost = (tax * (MilesK20)*2 )/100;
            String sTax = String.format("$%.2f", totalCost -18);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK20*2);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", ((MilesK20 + totalCost)*2) - 18);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("First");
            jtType.setText("ONE RETURN");
            jtAdult.setText("NIL");
            jtChild.setText("ONE"); 
        }
        
    //=========First Class================Middlesex================
        else if ((jRbFirst.isSelected()) && (jRbSingle.isSelected()) && (jRbAdultYes.isSelected()) && jComboBox1.getSelectedItem().equals("Middlesex"))
        {
            totalCost = (tax * (MilesK30 + fclass))/100;
            String sTax = String.format("$%.2f", totalCost);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK30 + fclass);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", MilesK30 + fclass +totalCost);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("First");
            jtType.setText("ONE MAY");
            jtAdult.setText("ONE");
            jtChild.setText("NIL");  
        }
        else if ((jRbFirst.isSelected()) && (jRbReturn.isSelected()) && (jRbAdultYes.isSelected()) && jComboBox1.getSelectedItem().equals("Middlesex"))
        {
            totalCost = (tax * (MilesK30)*2 )/100;
            String sTax = String.format("$%.2f", totalCost);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK30*2);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", (MilesK30 + totalCost)*2 );
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("First");
            jtType.setText("RETURN");
            jtAdult.setText("ONE");
            jtChild.setText("NIL"); 
        }
        else if ((jRbFirst.isSelected()) && (jRbSingle.isSelected()) && (jRbChildYes.isSelected()) && jComboBox1.getSelectedItem().equals("Middlesex"))
        {
            totalCost = (tax * (MilesK30 + fclass))/100;
            String sTax = String.format("$%.2f", totalCost -18);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK30 + fclass);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", (MilesK30 + fclass + totalCost) -18);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("First");
            jtType.setText("ONE WAY");
            jtAdult.setText("NIL");
            jtChild.setText("ONE"); 
        }
        else if ((jRbFirst.isSelected()) && (jRbReturn.isSelected()) && (jRbChildYes.isSelected()) && jComboBox1.getSelectedItem().equals("Middlesex"))
        {
            totalCost = (tax * (MilesK30)*2 )/100;
            String sTax = String.format("$%.2f", totalCost -18);
            jtTax.setText(sTax);
            String subTotal = String.format("$%.2f", MilesK30*2);
            jtSubTotal.setText(subTotal);
            String Total = String.format("$%.2f", ((MilesK30 + totalCost)*2) - 18);
            jtTotal.setText(Total);
            jtPrice.setText(Total);
            jtClass.setText("First");
            jtType.setText("ONE RETURN");
            jtAdult.setText("NIL");
            jtChild.setText("ONE"); 
        }
        
        
    }//GEN-LAST:event_btnTotalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JTextField jDate;
    private javax.swing.JTextField jFrom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRbAdultYes;
    private javax.swing.JRadioButton jRbChildYes;
    private javax.swing.JRadioButton jRbEco;
    private javax.swing.JRadioButton jRbFirst;
    private javax.swing.JRadioButton jRbReturn;
    private javax.swing.JRadioButton jRbSingle;
    private javax.swing.JRadioButton jRbStd;
    private javax.swing.JTextField jTime;
    private javax.swing.JTextField jTo;
    private javax.swing.JTextField jtAdult;
    private javax.swing.JTextField jtChild;
    private javax.swing.JTextField jtClass;
    private javax.swing.JTextField jtPrice;
    private javax.swing.JTextField jtRoute;
    private javax.swing.JTextField jtSubTotal;
    private javax.swing.JTextField jtTNo;
    private javax.swing.JTextField jtTax;
    private javax.swing.JTextField jtTotal;
    private javax.swing.JTextField jtType;
    // End of variables declaration//GEN-END:variables
}
